#define  CV_8U   0
#define  CV_8S   1
#define  CV_16U   2
#define  CV_16S   3
#define  CV_32S   4
#define  CV_32F   5
#define  CV_64F   6
#define  CV_8UC1   0
#define  CV_8UC2   8
#define  CV_8UC3   16
#define  CV_32FC1   5
#define  CV_32FC2   13
#define  CV_32FC3   21
#define  CV_32SC1   4
#define  CV_32SC2   12
#define  CV_32SC3   20
#define  CV_USRTYPE1   7
#define  FILLED   -1
#define  LINE_AA   16
#define  LINE_8   8
#define  LINE_4   4
#define  REDUCE_SUM   0
#define  REDUCE_AVG   1
#define  REDUCE_MAX   2
#define  REDUCE_MIN   3
#define  KIND_SHIFT   16
#define  CV_AA   16
#define  CV_TERMCRIT_ITER   1
#define  CV_TERMCRIT_NUMB   CV_TERMCRIT_ITER
#define  CV_TERMCRIT_EPS   2
#define  CV_C   1
#define  CV_L1   2
#define  CV_L2   4
#define  CV_NORM_MASK   7
#define  CV_RELATIVE   8
#define  CV_DIFF   16
#define  CV_MINMAX   32
#define  CV_DIFF_C   (CV_DIFF or CV_C)
#define  CV_DIFF_L1   (CV_DIFF or CV_L1)
#define  CV_DIFF_L2   (CV_DIFF or CV_L2)
#define  CV_RELATIVE_C   (CV_RELATIVE or CV_C)
#define  CV_RELATIVE_L1   (CV_RELATIVE or CV_L1)
#define  CV_RELATIVE_L2   (CV_RELATIVE or CV_L2)
#define  CV_MOP_ERODE   0
#define  CV_MOP_DILATE   1
#define  CV_MOP_OPEN   2
#define  CV_MOP_CLOSE   3
#define  CV_MOP_GRADIENT   49
#define  CV_MOP_TOPHAT   5
#define  CV_MOP_BLACKHAT   6
#define  CV_SHAPE_RECT   0
#define  CV_SHAPE_CROSS   1
#define  CV_SHAPE_ELLIPSE   2
#define  CV_SHAPE_CUSTOM   100
#define  CV_MAT_CONT_FLAG   16384
#define  CV_SUBMAT_FLAG   32768
#define  CV_MAX_DIM   32
#define  CV_INTER_NN   0
#define  CV_INTER_LINEAR   1
#define  CV_INTER_CUBIC   2
#define  CV_INTER_AREA   3
#define  CV_INTER_LANCZOS4   4
#define  CV_WARP_INVERSE_MAP   16
#define  CV_THRESH_BINARY   0
#define  CV_THRESH_BINARY_INV   1
#define  CV_THRESH_TRUNC   2
#define  CV_THRESH_TOZERO   3
#define  CV_THRESH_TOZERO_INV   4
#define  CV_THRESH_MASK   7
#define  CV_THRESH_OTSU   8
#define  CV_RETR_EXTERNAL   0
#define  CV_RETR_LIST   1
#define  CV_RETR_CCOMP   2
#define  CV_RETR_TREE   3
#define  CV_RETR_FLOODFILL   4
#define  CV_CHAIN_APPROX_NONE   1
#define  CV_CHAIN_APPROX_SIMPLE   2
#define  CV_CHAIN_APPROX_TC89_L1   3
#define  CV_CHAIN_APPROX_TC89_KCOS   4
#define  CV_WND_PROP_FULLSCREEN   0
#define  CV_WND_PROP_AUTOSIZE   1
#define  CV_WND_PROP_ASPECTRATIO   2
#define  CV_WND_PROP_OPENGL   3
#define  CV_WINDOW_NORMAL   0
#define  CV_WINDOW_AUTOSIZE   1
#define  CV_WINDOW_OPENGL   4096
#define  CV_INPAINT_NS   0
#define  CV_INPAINT_TELEA   1
#define  IPL_BORDER_CONSTANT   0
#define  IPL_BORDER_REPLICATE   1
#define  IPL_BORDER_REFLECT   2
#define  IPL_BORDER_WRAP   3
#define  IPL_BORDER_REFLECT_101   4
#define  IPL_BORDER_TRANSPARENT   5
#define  CV_LMEDS   4
#define  CV_RANSAC   8
#define  CV_FM_LMEDS   CV_LMEDS
#define  CV_FM_RANSAC   CV_RANSAC
#define  CV_FM_7POINT   1
#define  CV_FM_8POINT   2
#define  CV_CALIB_USE_INTRINSIC_GUESS   1
#define  CV_CALIB_FIX_ASPECT_RATIO   2
#define  CV_CALIB_FIX_PRINCIPAL_POINT   4
#define  CV_CALIB_ZERO_TANGENT_DIST   8
#define  CV_CALIB_FIX_FOCAL_LENGTH   16
#define  CV_CALIB_FIX_K1   32
#define  CV_CALIB_FIX_K2   64
#define  CV_CALIB_FIX_K3   128
#define  CV_CALIB_FIX_K4   2048
#define  CV_CALIB_FIX_K5   4096
#define  CV_CALIB_FIX_K6   8192
#define  CV_CALIB_RATIONAL_MODEL   16384
#define  CV_CALIB_FIX_INTRINSIC   256
#define  CV_CALIB_SAME_FOCAL_LENGTH   512
#define  CV_CALIB_ZERO_DISPARITY   1024
#define  CV_LKFLOW_INITIAL_GUESSES   4
#define  CV_LKFLOW_GET_MIN_EIGENVALS   8
#define  CV_HAAR_DO_CANNY_PRUNING   1
#define  CV_HAAR_SCALE_IMAGE   2
#define  CV_HAAR_FIND_BIGGEST_OBJECT   4
#define  CV_HAAR_DO_ROUGH_SEARCH   8
#define  cv_DECOMP_LU   0
#define  cv_DECOMP_SVD   1
#define  cv_DECOMP_EIG   2
#define  cv_DECOMP_CHOLESKY   3
#define  cv_DECOMP_QR   4
#define  cv_DECOMP_NORMAL   16
#define  cv_NORM_INF   1
#define  cv_NORM_L1   2
#define  cv_NORM_L2   4
#define  cv_NORM_L2SQR   5
#define  cv_NORM_HAMMING   6
#define  cv_NORM_HAMMING2   7
#define  cv_NORM_TYPE_MASK   7
#define  cv_NORM_RELATIVE   8
#define  cv_NORM_MINMAX   32
#define  cv_CMP_EQ   0
#define  cv_CMP_GT   1
#define  cv_CMP_GE   2
#define  cv_CMP_LT   3
#define  cv_CMP_LE   4
#define  cv_CMP_NE   5
#define  cv_GEMM_1_T   1
#define  cv_GEMM_2_T   2
#define  cv_GEMM_3_T   4
#define  cv_DFT_INVERSE   1
#define  cv_DFT_SCALE   2
#define  cv_DFT_ROWS   4
#define  cv_DFT_COMPLEX_OUTPUT   16
#define  cv_DFT_REAL_OUTPUT   32
#define  cv_DCT_INVERSE   DFT_INVERSE
#define  cv_DCT_ROWS   DFT_ROWS
#define  cv__InputArray_KIND_SHIFT   16
#define  cv__InputArray_FIXED_TYPE   0x8000 << KIND_SHIFT
#define  cv__InputArray_FIXED_SIZE   0x4000 << KIND_SHIFT
#define  cv__InputArray_KIND_MASK   ~(FIXED_TYPE|FIXED_SIZE) - (1 << KIND_SHIFT) + 1
#define  cv__InputArray_NONE   0 << KIND_SHIFT
#define  cv__InputArray_MAT   1 << KIND_SHIFT
#define  cv__InputArray_MATX   2 << KIND_SHIFT
#define  cv__InputArray_STD_VECTOR   3 << KIND_SHIFT
#define  cv__InputArray_STD_VECTOR_VECTOR   4 << KIND_SHIFT
#define  cv__InputArray_STD_VECTOR_MAT   5 << KIND_SHIFT
#define  cv__InputArray_EXPR   6 << KIND_SHIFT
#define  cv__InputArray_OPENGL_BUFFER   7 << KIND_SHIFT
#define  cv__InputArray_OPENGL_TEXTURE   8 << KIND_SHIFT
#define  cv__InputArray_GPU_MAT   9 << KIND_SHIFT
#define  cv__InputArray_OCL_MAT   10 << KIND_SHIFT
#define  cv_DEPTH_MASK_8U   1 << CV_8U
#define  cv_DEPTH_MASK_8S   1 << CV_8S
#define  cv_DEPTH_MASK_16U   1 << CV_16U
#define  cv_DEPTH_MASK_16S   1 << CV_16S
#define  cv_DEPTH_MASK_32S   1 << CV_32S
#define  cv_DEPTH_MASK_32F   1 << CV_32F
#define  cv_DEPTH_MASK_64F   1 << CV_64F
#define  cv_DEPTH_MASK_ALL   (DEPTH_MASK_64F<<1)-1
#define  cv_DEPTH_MASK_ALL_BUT_8S   DEPTH_MASK_ALL & ~DEPTH_MASK_8S
#define  cv_DEPTH_MASK_FLT   DEPTH_MASK_32F + DEPTH_MASK_64F
#define  cv_MAGIC_MASK   0xFFFF0000
#define  cv_TYPE_MASK   0x00000FFF
#define  cv_DEPTH_MASK   7
#define  cv_Mat_MAGIC_VAL   0x42FF0000
#define  cv_Mat_AUTO_STEP   0
#define  cv_Mat_CONTINUOUS_FLAG   CV_MAT_CONT_FLAG
#define  cv_Mat_SUBMATRIX_FLAG   CV_SUBMAT_FLAG
#define  cv_RNG_UNIFORM   0
#define  cv_RNG_NORMAL   1
#define  cv_TermCriteria_COUNT   1
#define  cv_TermCriteria_MAX_ITER   COUNT
#define  cv_TermCriteria_EPS   2
#define  cv_SORT_EVERY_ROW   0
#define  cv_SORT_EVERY_COLUMN   1
#define  cv_SORT_ASCENDING   0
#define  cv_SORT_DESCENDING   16
#define  cv_COVAR_SCRAMBLED   0
#define  cv_COVAR_NORMAL   1
#define  cv_COVAR_USE_AVG   2
#define  cv_COVAR_SCALE   4
#define  cv_COVAR_ROWS   8
#define  cv_COVAR_COLS   16
#define  cv_SVD_MODIFY_A   1
#define  cv_SVD_NO_UV   2
#define  cv_SVD_FULL_UV   4
#define  cv_KMEANS_RANDOM_CENTERS   0
#define  cv_KMEANS_PP_CENTERS   2
#define  cv_KMEANS_USE_INITIAL_LABELS   1
#define  cv_MARKER_CROSS   0
#define  cv_MARKER_TILTED_CROSS   1
#define  cv_MARKER_STAR   2
#define  cv_MARKER_DIAMOND   3
#define  cv_MARKER_SQUARE   4
#define  cv_MARKER_TRIANGLE_UP   5
#define  cv_MARKER_TRIANGLE_DOWN   6
#define  cv_FONT_HERSHEY_SIMPLEX   0
#define  cv_FONT_HERSHEY_PLAIN   1
#define  cv_FONT_HERSHEY_DUPLEX   2
#define  cv_FONT_HERSHEY_COMPLEX   3
#define  cv_FONT_HERSHEY_TRIPLEX   4
#define  cv_FONT_HERSHEY_COMPLEX_SMALL   5
#define  cv_FONT_HERSHEY_SCRIPT_SIMPLEX   6
#define  cv_FONT_HERSHEY_SCRIPT_COMPLEX   7
#define  cv_FONT_ITALIC   16
#define  cv_SparseMat_MAGIC_VAL   0x42FD0000
#define  cv_SparseMat_MAX_DIM   CV_MAX_DIM
#define  cv_SparseMat_HASH_SCALE   0x5bd1e995
#define  cv_SparseMat_HASH_BIT   0x80000000
#define  cv_FileStorage_READ   0
#define  cv_FileStorage_WRITE   1
#define  cv_FileStorage_APPEND   2
#define  cv_FileStorage_MEMORY   4
#define  cv_FileStorage_FORMAT_MASK   (7<<3)
#define  cv_FileStorage_FORMAT_AUTO   0
#define  cv_FileStorage_FORMAT_XML   (1<<3)
#define  cv_FileStorage_FORMAT_YAML   (2<<3)
#define  cv_FileStorage_UNDEFINED   0
#define  cv_FileStorage_VALUE_EXPECTED   1
#define  cv_FileStorage_NAME_EXPECTED   2
#define  cv_FileStorage_INSIDE_MAP   4
#define  cv_FileNode_NONE   0
#define  cv_FileNode_INT   1
#define  cv_FileNode_REAL   2
#define  cv_FileNode_FLOAT   REAL
#define  cv_FileNode_STR   3
#define  cv_FileNode_STRING   STR
#define  cv_FileNode_REF   4
#define  cv_FileNode_SEQ   5
#define  cv_FileNode_MAP   6
#define  cv_FileNode_TYPE_MASK   7
#define  cv_FileNode_FLOW   8
#define  cv_FileNode_USER   16
#define  cv_FileNode_EMPTY   32
#define  cv_FileNode_NAMED   64
#define  cv_Param_INT   0
#define  cv_Param_BOOLEAN   1
#define  cv_Param_REAL   2
#define  cv_Param_STRING   3
#define  cv_Param_MAT   4
#define  cv_Param_MAT_VECTOR   5
#define  cv_Param_ALGORITHM   6
#define  cv_Param_FLOAT   7
#define  cv_Param_UNSIGNED_INT   8
#define  cv_Param_UINT64   9
#define  cv_Param_SHORT   10
#define  cv_Param_UCHAR   11
#define  CvParamGrid_SVM_C   0
#define  CvParamGrid_SVM_GAMMA   1
#define  CvParamGrid_SVM_P   2
#define  CvParamGrid_SVM_NU   3
#define  CvParamGrid_SVM_COEF   4
#define  CvParamGrid_SVM_DEGREE   5
#define  CvSVM_C_SVC   100
#define  CvSVM_NU_SVC   101
#define  CvSVM_ONE_CLASS   102
#define  CvSVM_EPS_SVR   103
#define  CvSVM_NU_SVR   104
#define  CvSVM_LINEAR   0
#define  CvSVM_POLY   1
#define  CvSVM_RBF   2
#define  CvSVM_SIGMOID   3
#define  CvSVM_C   0
#define  CvSVM_GAMMA   1
#define  CvSVM_P   2
#define  CvSVM_NU   3
#define  CvSVM_COEF   4
#define  CvSVM_DEGREE   5
#define  cv_EM_COV_MAT_SPHERICAL   0
#define  cv_EM_COV_MAT_DIAGONAL   1
#define  cv_EM_COV_MAT_GENERIC   2
#define  cv_EM_COV_MAT_DEFAULT   COV_MAT_DIAGONAL
#define  cv_EM_DEFAULT_NCLUSTERS   5
#define  cv_EM_DEFAULT_MAX_ITERS   100
#define  cv_EM_START_E_STEP   1
#define  cv_EM_START_M_STEP   2
#define  cv_EM_START_AUTO_STEP   0
#define  CvBoost_DISCRETE   0
#define  CvBoost_REAL   1
#define  CvBoost_LOGIT   2
#define  CvBoost_GENTLE   3
#define  CvBoost_DEFAULT   0
#define  CvBoost_GINI   1
#define  CvBoost_MISCLASS   3
#define  CvBoost_SQERR   4
#define  CvGBTrees_SQUARED_LOSS   0
#define  CvGBTrees_ABSOLUTE_LOSS   0+1
#define  CvGBTrees_HUBER_LOSS   3
#define  CvGBTrees_DEVIANCE_LOSS   3+1
#define  CvANN_MLP_TrainParams_BACKPROP   0
#define  CvANN_MLP_TrainParams_RPROP   1
#define  CvANN_MLP_IDENTITY   0
#define  CvANN_MLP_SIGMOID_SYM   1
#define  CvANN_MLP_GAUSSIAN   2
#define  CvANN_MLP_UPDATE_WEIGHTS   1
#define  CvANN_MLP_NO_INPUT_SCALE   2
#define  CvANN_MLP_NO_OUTPUT_SCALE   4
#define  cv_BORDER_REPLICATE   IPL_BORDER_REPLICATE
#define  cv_BORDER_CONSTANT   IPL_BORDER_CONSTANT
#define  cv_BORDER_REFLECT   IPL_BORDER_REFLECT
#define  cv_BORDER_WRAP   IPL_BORDER_WRAP
#define  cv_BORDER_REFLECT_101   IPL_BORDER_REFLECT_101
#define  cv_BORDER_REFLECT101   BORDER_REFLECT_101
#define  cv_BORDER_TRANSPARENT   IPL_BORDER_TRANSPARENT
#define  cv_BORDER_DEFAULT   BORDER_REFLECT_101
#define  cv_BORDER_ISOLATED   16
#define  cv_KERNEL_GENERAL   0
#define  cv_KERNEL_SYMMETRICAL   1
#define  cv_KERNEL_ASYMMETRICAL   2
#define  cv_KERNEL_SMOOTH   4
#define  cv_KERNEL_INTEGER   8
#define  cv_MORPH_ERODE   CV_MOP_ERODE
#define  cv_MORPH_DILATE   CV_MOP_DILATE
#define  cv_MORPH_OPEN   CV_MOP_OPEN
#define  cv_MORPH_CLOSE   CV_MOP_CLOSE
#define  cv_MORPH_GRADIENT   CV_MOP_GRADIENT
#define  cv_MORPH_TOPHAT   CV_MOP_TOPHAT
#define  cv_MORPH_BLACKHAT   CV_MOP_BLACKHAT
#define  cv_MORPH_HITMISS   CV_MOP_BLACKHAT+1
#define  cv_MORPH_RECT   0
#define  cv_MORPH_CROSS   1
#define  cv_MORPH_ELLIPSE   2
#define  cv_GHT_POSITION   0
#define  cv_GHT_SCALE   1
#define  cv_GHT_ROTATION   2
#define  cv_INTER_NEAREST   CV_INTER_NN
#define  cv_INTER_LINEAR   CV_INTER_LINEAR
#define  cv_INTER_CUBIC   CV_INTER_CUBIC
#define  cv_INTER_AREA   CV_INTER_AREA
#define  cv_INTER_LANCZOS4   CV_INTER_LANCZOS4
#define  cv_INTER_MAX   7
#define  cv_WARP_INVERSE_MAP   CV_WARP_INVERSE_MAP
#define  cv_INTER_BITS   5
#define  cv_INTER_BITS2   INTER_BITS*2
#define  cv_INTER_TAB_SIZE   (1<<INTER_BITS)
#define  cv_INTER_TAB_SIZE2   INTER_TAB_SIZE*INTER_TAB_SIZE
#define  cv_THRESH_BINARY   CV_THRESH_BINARY
#define  cv_THRESH_BINARY_INV   CV_THRESH_BINARY_INV
#define  cv_THRESH_TRUNC   CV_THRESH_TRUNC
#define  cv_THRESH_TOZERO   CV_THRESH_TOZERO
#define  cv_THRESH_TOZERO_INV   CV_THRESH_TOZERO_INV
#define  cv_THRESH_MASK   CV_THRESH_MASK
#define  cv_THRESH_OTSU   CV_THRESH_OTSU
#define  cv_ADAPTIVE_THRESH_MEAN_C   0
#define  cv_ADAPTIVE_THRESH_GAUSSIAN_C   1
#define  cv_PROJ_SPHERICAL_ORTHO   0
#define  cv_PROJ_SPHERICAL_EQRECT   1
#define  cv_GC_BGD   0
#define  cv_GC_FGD   1
#define  cv_GC_PR_BGD   2
#define  cv_GC_PR_FGD   3
#define  cv_GC_INIT_WITH_RECT   0
#define  cv_GC_INIT_WITH_MASK   1
#define  cv_GC_EVAL   2
#define  cv_DIST_LABEL_CCOMP   0
#define  cv_DIST_LABEL_PIXEL   1
#define  cv_FLOODFILL_FIXED_RANGE   1 << 16
#define  cv_FLOODFILL_MASK_ONLY   1 << 17
#define  cv_COLOR_BGR2BGRA   0
#define  cv_COLOR_RGB2RGBA   COLOR_BGR2BGRA
#define  cv_COLOR_BGRA2BGR   1
#define  cv_COLOR_RGBA2RGB   COLOR_BGRA2BGR
#define  cv_COLOR_BGR2RGBA   2
#define  cv_COLOR_RGB2BGRA   COLOR_BGR2RGBA
#define  cv_COLOR_RGBA2BGR   3
#define  cv_COLOR_BGRA2RGB   COLOR_RGBA2BGR
#define  cv_COLOR_BGR2RGB   4
#define  cv_COLOR_RGB2BGR   COLOR_BGR2RGB
#define  cv_COLOR_BGRA2RGBA   5
#define  cv_COLOR_RGBA2BGRA   COLOR_BGRA2RGBA
#define  cv_COLOR_BGR2GRAY   6
#define  cv_COLOR_RGB2GRAY   7
#define  cv_COLOR_GRAY2BGR   8
#define  cv_COLOR_GRAY2RGB   COLOR_GRAY2BGR
#define  cv_COLOR_GRAY2BGRA   9
#define  cv_COLOR_GRAY2RGBA   COLOR_GRAY2BGRA
#define  cv_COLOR_BGRA2GRAY   10
#define  cv_COLOR_RGBA2GRAY   11
#define  cv_COLOR_BGR2BGR565   12
#define  cv_COLOR_RGB2BGR565   13
#define  cv_COLOR_BGR5652BGR   14
#define  cv_COLOR_BGR5652RGB   15
#define  cv_COLOR_BGRA2BGR565   16
#define  cv_COLOR_RGBA2BGR565   17
#define  cv_COLOR_BGR5652BGRA   18
#define  cv_COLOR_BGR5652RGBA   19
#define  cv_COLOR_GRAY2BGR565   20
#define  cv_COLOR_BGR5652GRAY   21
#define  cv_COLOR_BGR2BGR555   22
#define  cv_COLOR_RGB2BGR555   23
#define  cv_COLOR_BGR5552BGR   24
#define  cv_COLOR_BGR5552RGB   25
#define  cv_COLOR_BGRA2BGR555   26
#define  cv_COLOR_RGBA2BGR555   27
#define  cv_COLOR_BGR5552BGRA   28
#define  cv_COLOR_BGR5552RGBA   29
#define  cv_COLOR_GRAY2BGR555   30
#define  cv_COLOR_BGR5552GRAY   31
#define  cv_COLOR_BGR2XYZ   32
#define  cv_COLOR_RGB2XYZ   33
#define  cv_COLOR_XYZ2BGR   34
#define  cv_COLOR_XYZ2RGB   35
#define  cv_COLOR_BGR2YCrCb   36
#define  cv_COLOR_RGB2YCrCb   37
#define  cv_COLOR_YCrCb2BGR   38
#define  cv_COLOR_YCrCb2RGB   39
#define  cv_COLOR_BGR2HSV   40
#define  cv_COLOR_RGB2HSV   41
#define  cv_COLOR_BGR2Lab   44
#define  cv_COLOR_RGB2Lab   45
#define  cv_COLOR_BayerBG2BGR   46
#define  cv_COLOR_BayerGB2BGR   47
#define  cv_COLOR_BayerRG2BGR   48
#define  cv_COLOR_BayerGR2BGR   49
#define  cv_COLOR_BayerBG2RGB   COLOR_BayerRG2BGR
#define  cv_COLOR_BayerGB2RGB   COLOR_BayerGR2BGR
#define  cv_COLOR_BayerRG2RGB   COLOR_BayerBG2BGR
#define  cv_COLOR_BayerGR2RGB   COLOR_BayerGB2BGR
#define  cv_COLOR_BGR2Luv   50
#define  cv_COLOR_RGB2Luv   51
#define  cv_COLOR_BGR2HLS   52
#define  cv_COLOR_RGB2HLS   53
#define  cv_COLOR_HSV2BGR   54
#define  cv_COLOR_HSV2RGB   55
#define  cv_COLOR_Lab2BGR   56
#define  cv_COLOR_Lab2RGB   57
#define  cv_COLOR_Luv2BGR   58
#define  cv_COLOR_Luv2RGB   59
#define  cv_COLOR_HLS2BGR   60
#define  cv_COLOR_HLS2RGB   61
#define  cv_COLOR_BayerBG2BGR_VNG   62
#define  cv_COLOR_BayerGB2BGR_VNG   63
#define  cv_COLOR_BayerRG2BGR_VNG   64
#define  cv_COLOR_BayerGR2BGR_VNG   65
#define  cv_COLOR_BayerBG2RGB_VNG   COLOR_BayerRG2BGR_VNG
#define  cv_COLOR_BayerGB2RGB_VNG   COLOR_BayerGR2BGR_VNG
#define  cv_COLOR_BayerRG2RGB_VNG   COLOR_BayerBG2BGR_VNG
#define  cv_COLOR_BayerGR2RGB_VNG   COLOR_BayerGB2BGR_VNG
#define  cv_COLOR_BGR2HSV_FULL   66
#define  cv_COLOR_RGB2HSV_FULL   67
#define  cv_COLOR_BGR2HLS_FULL   68
#define  cv_COLOR_RGB2HLS_FULL   69
#define  cv_COLOR_HSV2BGR_FULL   70
#define  cv_COLOR_HSV2RGB_FULL   71
#define  cv_COLOR_HLS2BGR_FULL   72
#define  cv_COLOR_HLS2RGB_FULL   73
#define  cv_COLOR_LBGR2Lab   74
#define  cv_COLOR_LRGB2Lab   75
#define  cv_COLOR_LBGR2Luv   76
#define  cv_COLOR_LRGB2Luv   77
#define  cv_COLOR_Lab2LBGR   78
#define  cv_COLOR_Lab2LRGB   79
#define  cv_COLOR_Luv2LBGR   80
#define  cv_COLOR_Luv2LRGB   81
#define  cv_COLOR_BGR2YUV   82
#define  cv_COLOR_RGB2YUV   83
#define  cv_COLOR_YUV2BGR   84
#define  cv_COLOR_YUV2RGB   85
#define  cv_COLOR_BayerBG2GRAY   86
#define  cv_COLOR_BayerGB2GRAY   87
#define  cv_COLOR_BayerRG2GRAY   88
#define  cv_COLOR_BayerGR2GRAY   89
#define  cv_COLOR_YUV2RGB_NV12   90
#define  cv_COLOR_YUV2BGR_NV12   91
#define  cv_COLOR_YUV2RGB_NV21   92
#define  cv_COLOR_YUV2BGR_NV21   93
#define  cv_COLOR_YUV420sp2RGB   COLOR_YUV2RGB_NV21
#define  cv_COLOR_YUV420sp2BGR   COLOR_YUV2BGR_NV21
#define  cv_COLOR_YUV2RGBA_NV12   94
#define  cv_COLOR_YUV2BGRA_NV12   95
#define  cv_COLOR_YUV2RGBA_NV21   96
#define  cv_COLOR_YUV2BGRA_NV21   97
#define  cv_COLOR_YUV420sp2RGBA   COLOR_YUV2RGBA_NV21
#define  cv_COLOR_YUV420sp2BGRA   COLOR_YUV2BGRA_NV21
#define  cv_COLOR_YUV2RGB_YV12   98
#define  cv_COLOR_YUV2BGR_YV12   99
#define  cv_COLOR_YUV2RGB_IYUV   100
#define  cv_COLOR_YUV2BGR_IYUV   101
#define  cv_COLOR_YUV2RGB_I420   COLOR_YUV2RGB_IYUV
#define  cv_COLOR_YUV2BGR_I420   COLOR_YUV2BGR_IYUV
#define  cv_COLOR_YUV420p2RGB   COLOR_YUV2RGB_YV12
#define  cv_COLOR_YUV420p2BGR   COLOR_YUV2BGR_YV12
#define  cv_COLOR_YUV2RGBA_YV12   102
#define  cv_COLOR_YUV2BGRA_YV12   103
#define  cv_COLOR_YUV2RGBA_IYUV   104
#define  cv_COLOR_YUV2BGRA_IYUV   105
#define  cv_COLOR_YUV2RGBA_I420   COLOR_YUV2RGBA_IYUV
#define  cv_COLOR_YUV2BGRA_I420   COLOR_YUV2BGRA_IYUV
#define  cv_COLOR_YUV420p2RGBA   COLOR_YUV2RGBA_YV12
#define  cv_COLOR_YUV420p2BGRA   COLOR_YUV2BGRA_YV12
#define  cv_COLOR_YUV2GRAY_420   106
#define  cv_COLOR_YUV2GRAY_NV21   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV2GRAY_NV12   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV2GRAY_YV12   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV2GRAY_IYUV   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV2GRAY_I420   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV420sp2GRAY   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV420p2GRAY   COLOR_YUV2GRAY_420
#define  cv_COLOR_YUV2RGB_UYVY   107
#define  cv_COLOR_YUV2BGR_UYVY   108
#define  cv_COLOR_YUV2RGB_Y422   COLOR_YUV2RGB_UYVY
#define  cv_COLOR_YUV2BGR_Y422   COLOR_YUV2BGR_UYVY
#define  cv_COLOR_YUV2RGB_UYNV   COLOR_YUV2RGB_UYVY
#define  cv_COLOR_YUV2BGR_UYNV   COLOR_YUV2BGR_UYVY
#define  cv_COLOR_YUV2RGBA_UYVY   111
#define  cv_COLOR_YUV2BGRA_UYVY   112
#define  cv_COLOR_YUV2RGBA_Y422   COLOR_YUV2RGBA_UYVY
#define  cv_COLOR_YUV2BGRA_Y422   COLOR_YUV2BGRA_UYVY
#define  cv_COLOR_YUV2RGBA_UYNV   COLOR_YUV2RGBA_UYVY
#define  cv_COLOR_YUV2BGRA_UYNV   COLOR_YUV2BGRA_UYVY
#define  cv_COLOR_YUV2RGB_YUY2   115
#define  cv_COLOR_YUV2BGR_YUY2   116
#define  cv_COLOR_YUV2RGB_YVYU   117
#define  cv_COLOR_YUV2BGR_YVYU   118
#define  cv_COLOR_YUV2RGB_YUYV   COLOR_YUV2RGB_YUY2
#define  cv_COLOR_YUV2BGR_YUYV   COLOR_YUV2BGR_YUY2
#define  cv_COLOR_YUV2RGB_YUNV   COLOR_YUV2RGB_YUY2
#define  cv_COLOR_YUV2BGR_YUNV   COLOR_YUV2BGR_YUY2
#define  cv_COLOR_YUV2RGBA_YUY2   119
#define  cv_COLOR_YUV2BGRA_YUY2   120
#define  cv_COLOR_YUV2RGBA_YVYU   121
#define  cv_COLOR_YUV2BGRA_YVYU   122
#define  cv_COLOR_YUV2RGBA_YUYV   COLOR_YUV2RGBA_YUY2
#define  cv_COLOR_YUV2BGRA_YUYV   COLOR_YUV2BGRA_YUY2
#define  cv_COLOR_YUV2RGBA_YUNV   COLOR_YUV2RGBA_YUY2
#define  cv_COLOR_YUV2BGRA_YUNV   COLOR_YUV2BGRA_YUY2
#define  cv_COLOR_YUV2GRAY_UYVY   123
#define  cv_COLOR_YUV2GRAY_YUY2   124
#define  cv_COLOR_YUV2GRAY_Y422   COLOR_YUV2GRAY_UYVY
#define  cv_COLOR_YUV2GRAY_UYNV   COLOR_YUV2GRAY_UYVY
#define  cv_COLOR_YUV2GRAY_YVYU   COLOR_YUV2GRAY_YUY2
#define  cv_COLOR_YUV2GRAY_YUYV   COLOR_YUV2GRAY_YUY2
#define  cv_COLOR_YUV2GRAY_YUNV   COLOR_YUV2GRAY_YUY2
#define  cv_COLOR_RGBA2mRGBA   125
#define  cv_COLOR_mRGBA2RGBA   126
#define  cv_COLOR_RGB2YUV_I420   127
#define  cv_COLOR_BGR2YUV_I420   128
#define  cv_COLOR_RGB2YUV_IYUV   COLOR_RGB2YUV_I420
#define  cv_COLOR_BGR2YUV_IYUV   COLOR_BGR2YUV_I420
#define  cv_COLOR_RGBA2YUV_I420   129
#define  cv_COLOR_BGRA2YUV_I420   130
#define  cv_COLOR_RGBA2YUV_IYUV   COLOR_RGBA2YUV_I420
#define  cv_COLOR_BGRA2YUV_IYUV   COLOR_BGRA2YUV_I420
#define  cv_COLOR_RGB2YUV_YV12   131
#define  cv_COLOR_BGR2YUV_YV12   132
#define  cv_COLOR_RGBA2YUV_YV12   133
#define  cv_COLOR_BGRA2YUV_YV12   134
#define  cv_COLOR_COLORCVT_MAX   135
#define  cv_TM_SQDIFF   0
#define  cv_TM_SQDIFF_NORMED   1
#define  cv_TM_CCORR   2
#define  cv_TM_CCORR_NORMED   3
#define  cv_TM_CCOEFF   4
#define  cv_TM_CCOEFF_NORMED   5
#define  cv_RETR_EXTERNAL   CV_RETR_EXTERNAL
#define  cv_RETR_LIST   CV_RETR_LIST
#define  cv_RETR_CCOMP   CV_RETR_CCOMP
#define  cv_RETR_TREE   CV_RETR_TREE
#define  cv_RETR_FLOODFILL   CV_RETR_FLOODFILL
#define  cv_CHAIN_APPROX_NONE   CV_CHAIN_APPROX_NONE
#define  cv_CHAIN_APPROX_SIMPLE   CV_CHAIN_APPROX_SIMPLE
#define  cv_CHAIN_APPROX_TC89_L1   CV_CHAIN_APPROX_TC89_L1
#define  cv_CHAIN_APPROX_TC89_KCOS   CV_CHAIN_APPROX_TC89_KCOS
#define  cv_Subdiv2D_PTLOC_ERROR   -2
#define  cv_Subdiv2D_PTLOC_OUTSIDE_RECT   -1
#define  cv_Subdiv2D_PTLOC_INSIDE   0
#define  cv_Subdiv2D_PTLOC_VERTEX   1
#define  cv_Subdiv2D_PTLOC_ON_EDGE   2
#define  cv_Subdiv2D_NEXT_AROUND_ORG   0x00
#define  cv_Subdiv2D_NEXT_AROUND_DST   0x22
#define  cv_Subdiv2D_PREV_AROUND_ORG   0x11
#define  cv_Subdiv2D_PREV_AROUND_DST   0x33
#define  cv_Subdiv2D_NEXT_AROUND_LEFT   0x13
#define  cv_Subdiv2D_NEXT_AROUND_RIGHT   0x31
#define  cv_Subdiv2D_PREV_AROUND_LEFT   0x20
#define  cv_Subdiv2D_PREV_AROUND_RIGHT   0x02
#define  CV_ITERATIVE   0
#define  CV_EPNP   1
#define  CV_P3P   2
#define  CvLevMarq_DONE   0
#define  CvLevMarq_STARTED   1
#define  CvLevMarq_CALC_J   2
#define  CvLevMarq_CHECK_ERR   3
#define  cv_LMEDS   CV_LMEDS
#define  cv_RANSAC   CV_RANSAC
#define  cv_ITERATIVE   CV_ITERATIVE
#define  cv_EPNP   CV_EPNP
#define  cv_P3P   CV_P3P
#define  cv_CALIB_CB_ADAPTIVE_THRESH   1
#define  cv_CALIB_CB_NORMALIZE_IMAGE   2
#define  cv_CALIB_CB_FILTER_QUADS   4
#define  cv_CALIB_CB_FAST_CHECK   8
#define  cv_CALIB_CB_SYMMETRIC_GRID   1
#define  cv_CALIB_CB_ASYMMETRIC_GRID   2
#define  cv_CALIB_CB_CLUSTERING   4
#define  cv_CALIB_USE_INTRINSIC_GUESS   CV_CALIB_USE_INTRINSIC_GUESS
#define  cv_CALIB_FIX_ASPECT_RATIO   CV_CALIB_FIX_ASPECT_RATIO
#define  cv_CALIB_FIX_PRINCIPAL_POINT   CV_CALIB_FIX_PRINCIPAL_POINT
#define  cv_CALIB_ZERO_TANGENT_DIST   CV_CALIB_ZERO_TANGENT_DIST
#define  cv_CALIB_FIX_FOCAL_LENGTH   CV_CALIB_FIX_FOCAL_LENGTH
#define  cv_CALIB_FIX_K1   CV_CALIB_FIX_K1
#define  cv_CALIB_FIX_K2   CV_CALIB_FIX_K2
#define  cv_CALIB_FIX_K3   CV_CALIB_FIX_K3
#define  cv_CALIB_FIX_K4   CV_CALIB_FIX_K4
#define  cv_CALIB_FIX_K5   CV_CALIB_FIX_K5
#define  cv_CALIB_FIX_K6   CV_CALIB_FIX_K6
#define  cv_CALIB_RATIONAL_MODEL   CV_CALIB_RATIONAL_MODEL
#define  cv_CALIB_FIX_INTRINSIC   CV_CALIB_FIX_INTRINSIC
#define  cv_CALIB_SAME_FOCAL_LENGTH   CV_CALIB_SAME_FOCAL_LENGTH
#define  cv_CALIB_ZERO_DISPARITY   CV_CALIB_ZERO_DISPARITY
#define  cv_FM_7POINT   CV_FM_7POINT
#define  cv_FM_8POINT   CV_FM_8POINT
#define  cv_FM_LMEDS   CV_FM_LMEDS
#define  cv_FM_RANSAC   CV_FM_RANSAC
#define  cv_StereoBM_PREFILTER_NORMALIZED_RESPONSE   0
#define  cv_StereoBM_PREFILTER_XSOBEL   1
#define  cv_StereoBM_BASIC_PRESET   0
#define  cv_StereoBM_FISH_EYE_PRESET   1
#define  cv_StereoBM_NARROW_PRESET   2
#define  cv_StereoSGBM_DISP_SHIFT   4
#define  cv_StereoSGBM_DISP_SCALE   (1<<DISP_SHIFT)
#define  cv_fisheye_CALIB_USE_INTRINSIC_GUESS   1
#define  cv_fisheye_CALIB_RECOMPUTE_EXTRINSIC   2
#define  cv_fisheye_CALIB_CHECK_COND   4
#define  cv_fisheye_CALIB_FIX_SKEW   8
#define  cv_fisheye_CALIB_FIX_K1   16
#define  cv_fisheye_CALIB_FIX_K2   32
#define  cv_fisheye_CALIB_FIX_K3   64
#define  cv_fisheye_CALIB_FIX_K4   128
#define  cv_fisheye_CALIB_FIX_INTRINSIC   256
#define  cv_ORB_kBytes   32
#define  cv_ORB_HARRIS_SCORE   0
#define  cv_ORB_FAST_SCORE   1
#define  cv_FREAK_NB_SCALES   64
#define  cv_FREAK_NB_PAIRS   512
#define  cv_FREAK_NB_ORIENPAIRS   45
#define  cv_FastFeatureDetector_TYPE_5_8   0
#define  cv_FastFeatureDetector_TYPE_7_12   1
#define  cv_FastFeatureDetector_TYPE_9_16   2
#define  cv_Hamming_normType   NORM_HAMMING
#define  cv_DrawMatchesFlags_DEFAULT   0
#define  cv_DrawMatchesFlags_DRAW_OVER_OUTIMG   1
#define  cv_DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS   2
#define  cv_DrawMatchesFlags_DRAW_RICH_KEYPOINTS   4
#define  cv_OPTFLOW_USE_INITIAL_FLOW   CV_LKFLOW_INITIAL_GUESSES
#define  cv_OPTFLOW_LK_GET_MIN_EIGENVALS   CV_LKFLOW_GET_MIN_EIGENVALS
#define  cv_OPTFLOW_FARNEBACK_GAUSSIAN   256
#define  cv_INPAINT_NS   CV_INPAINT_NS
#define  cv_INPAINT_TELEA   CV_INPAINT_TELEA
#define  cv_FeatureEvaluator_HAAR   0
#define  cv_FeatureEvaluator_LBP   1
#define  cv_FeatureEvaluator_HOG   2
#define  cv_CASCADE_DO_CANNY_PRUNING   1
#define  cv_CASCADE_SCALE_IMAGE   2
#define  cv_CASCADE_FIND_BIGGEST_OBJECT   4
#define  cv_CASCADE_DO_ROUGH_SEARCH   8
#define  cv_HOGDescriptor_L2Hys   0
#define  cv_HOGDescriptor_DEFAULT_NLEVELS   64
#define  CvAdaptiveSkinDetector_MORPHING_METHOD_NONE   0
#define  CvAdaptiveSkinDetector_MORPHING_METHOD_ERODE   1
#define  CvAdaptiveSkinDetector_MORPHING_METHOD_ERODE_ERODE   2
#define  CvAdaptiveSkinDetector_MORPHING_METHOD_ERODE_DILATE   3
#define  CvFuzzyMeanShiftTracker_tsNone   0
#define  CvFuzzyMeanShiftTracker_tsSearching   1
#define  CvFuzzyMeanShiftTracker_tsTracking   2
#define  CvFuzzyMeanShiftTracker_tsSetWindow   3
#define  CvFuzzyMeanShiftTracker_tsDisabled   10
#define  CvFuzzyMeanShiftTracker_rmEdgeDensityLinear   0
#define  CvFuzzyMeanShiftTracker_rmEdgeDensityFuzzy   1
#define  CvFuzzyMeanShiftTracker_rmInnerDensity   2
#define  CvFuzzyMeanShiftTracker_MinKernelMass   1000
#define  cv_SelfSimDescriptor_DEFAULT_SMALL_SIZE   5
#define  cv_SelfSimDescriptor_DEFAULT_LARGE_SIZE   41
#define  cv_SelfSimDescriptor_DEFAULT_NUM_ANGLES   20
#define  cv_SelfSimDescriptor_DEFAULT_START_DISTANCE_BUCKET   3
#define  cv_SelfSimDescriptor_DEFAULT_NUM_DISTANCE_BUCKETS   7
#define  cv_StereoVar_USE_INITIAL_DISPARITY   1
#define  cv_StereoVar_USE_EQUALIZE_HIST   2
#define  cv_StereoVar_USE_SMART_ID   4
#define  cv_StereoVar_USE_AUTO_PARAMS   8
#define  cv_StereoVar_USE_MEDIAN_FILTERING   16
#define  cv_StereoVar_CYCLE_O   0
#define  cv_StereoVar_CYCLE_V   1
#define  cv_StereoVar_PENALIZATION_TICHONOV   0
#define  cv_StereoVar_PENALIZATION_CHARBONNIER   1
#define  cv_StereoVar_PENALIZATION_PERONA_MALIK   2
#define  cv_ROTATION   1
#define  cv_TRANSLATION   2
#define  cv_RIGID_BODY_MOTION   4
#define  cv_COLORMAP_AUTUMN   0
#define  cv_COLORMAP_BONE   1
#define  cv_COLORMAP_JET   2
#define  cv_COLORMAP_WINTER   3
#define  cv_COLORMAP_RAINBOW   4
#define  cv_COLORMAP_OCEAN   5
#define  cv_COLORMAP_SUMMER   6
#define  cv_COLORMAP_SPRING   7
#define  cv_COLORMAP_COOL   8
#define  cv_COLORMAP_HSV   9
#define  cv_COLORMAP_PINK   10
#define  cv_COLORMAP_HOT   11
#define  cv_WINDOW_NORMAL   CV_WINDOW_NORMAL
#define  cv_WINDOW_AUTOSIZE   CV_WINDOW_AUTOSIZE
#define  cv_WINDOW_OPENGL   CV_WINDOW_OPENGL
#define  cv_WND_PROP_FULLSCREEN   CV_WND_PROP_FULLSCREEN
#define  cv_WND_PROP_AUTOSIZE   CV_WND_PROP_AUTOSIZE
#define  cv_WND_PROP_ASPECT_RATIO   CV_WND_PROP_ASPECTRATIO
#define  cv_WND_PROP_OPENGL   CV_WND_PROP_OPENGL
#define  cv_EVENT_MOUSEMOVE   0
#define  cv_EVENT_LBUTTONDOWN   1
#define  cv_EVENT_RBUTTONDOWN   2
#define  cv_EVENT_MBUTTONDOWN   3
#define  cv_EVENT_LBUTTONUP   4
#define  cv_EVENT_RBUTTONUP   5
#define  cv_EVENT_MBUTTONUP   6
#define  cv_EVENT_LBUTTONDBLCLK   7
#define  cv_EVENT_RBUTTONDBLCLK   8
#define  cv_EVENT_MBUTTONDBLCLK   9
#define  cv_EVENT_FLAG_LBUTTON   1
#define  cv_EVENT_FLAG_RBUTTON   2
#define  cv_EVENT_FLAG_MBUTTON   4
#define  cv_EVENT_FLAG_CTRLKEY   8
#define  cv_EVENT_FLAG_SHIFTKEY   16
#define  cv_EVENT_FLAG_ALTKEY   32
#define  cv_IMREAD_UNCHANGED   -1
#define  cv_IMREAD_GRAYSCALE   0
#define  cv_IMREAD_COLOR   1
#define  cv_IMREAD_ANYDEPTH   2
#define  cv_IMREAD_ANYCOLOR   4
#define  cv_IMWRITE_JPEG_QUALITY   1
#define  cv_IMWRITE_PNG_COMPRESSION   16
#define  cv_IMWRITE_PNG_STRATEGY   17
#define  cv_IMWRITE_PNG_BILEVEL   18
#define  cv_IMWRITE_PNG_STRATEGY_DEFAULT   0
#define  cv_IMWRITE_PNG_STRATEGY_FILTERED   1
#define  cv_IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY   2
#define  cv_IMWRITE_PNG_STRATEGY_RLE   3
#define  cv_IMWRITE_PNG_STRATEGY_FIXED   4
#define  cv_IMWRITE_PXM_BINARY   32
